# Copyright 2015 Google Inc. All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to writing, software distributed
# under the License is distributed on a "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

application: bugover-7
module: frontend
version: v1
api_version: 1
runtime: python27
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static